quarkus.datasource.db-kind=postgresql

quarkus.hibernate-orm.schema-management.strategy=validate

# Flyway
quarkus.flyway.migrate-at-start=true

mp.openapi.extensions.smallrye.info.title=Game Vault API
mp.openapi.extensions.smallrye.info.version=1.0.0
mp.openapi.extensions.smallrye.info.description=API para gerenciamento de biblioteca de jogos pessoal
mp.openapi.extensions.smallrye.info.contact.name=Marcos Guisleri
mp.openapi.extensions.smallrye.info.contact.url=https://github.com/marcosguisleri